const items=[
    {
        id:`001`,
        title:`Clothes`,
        item_image:`box1.jpeg`,
        rating:{
            stars:`4.5*`,
            noOfReviews:'1.4k',
        },
        company_name:`Carlton London`,
        item_name:`Denim`,
        price:{
            current:600,
            original:900,
            discount:34,
        },
        day:4,
        buys:1200,
        
    },
    {
        id:`002`,
        title:`Health & Personal Care`,
        item_image:`box2.jpeg`,
        rating:{
            stars:`4.8*`,
            noOfReviews:'1.9k',
        },
        company_name:`Colgate`,
        item_name:`Toothbrush`,
        price:{
            current:125,
            original:251,
            discount:51,
        },
        day:2,
        buys:1500,
    },
    {
        id:`003`,
        title:`Furniture`,
        item_image:`box3.jpeg`,
        rating:{
            stars:`4.2*`,
            noOfReviews:'2.4k',
        },
        company_name:`Gothrej`,
        item_name:`Table`,
        price:{
            current:1600,
            original:2400,
            discount:33,
        },
        day:8,
        buys:900,
    },   
     {
        id:`004`,
        title:`Electronics`,
        item_image:`box4.jpeg`,
        rating:{
            stars:`4.4*`,
            noOfReviews:'1.8k',
        },
        company_name:`Vivo`,
        item_name:`Mobiles`,
        price:{
            current:15000,
            original:20000,
            discount:25,
        },
        day:7,
        buys:1150,
    },    
    {
        id:`005`,
        title:`Beauty Items`,
        item_image:`box5.jpeg`,
        rating:{
            stars:`4.8*`,
            noOfReviews:'6.1k',
        },
        company_name:`Fair & Lovely`,
        item_name:`Facial Creams`,
        price:{
            current:200,
            original:250,
            discount:20,
        },
        day:3,
        buys:600,
    },    {
        id:`006`,
        title:`Pet Care`,
        item_image:`box6.jpeg`,
        rating:{
            stars:`4.2*`,
            noOfReviews:'1.7k',
        },
        company_name:`Pit Bull`,
        item_name:`Pet Animals Care`,
        price:{
            current:5999,
            original:8000,
            discount:25,
        },
        day:8,
        buys:900,
    },    {
        id:`007`,
        title:`Toys`,
        item_image:`box7.jpeg`,
        rating:{
            stars:`4.7*`,
            noOfReviews:'12.5k',
        },
        company_name:`Cartoon Network`,
        item_name:`Toys`,
        price:{
            current:199,
            original:500,
            discount:60,
        },
        day:2,
        buys:1000,
    },    {
        id:`008`,
        title:`Fashion Trends`,
        item_image:`box8.jpeg`,
        rating:{
            stars:`4.5*`,
            noOfReviews:'1.4k',
        },
        company_name:`Dhavak`,
        item_name:`Stylish Clothes`,
        price:{
            current:1999,
            original:3999,
            discount:50,
        },
        day:7,
        buys:1100,
    },   
]